function [safe_results] = ase_preprocess(results)

safe_list = {'bed_pow', ...
            'bed_pow_calib', ...
            'bed_pow_xover', ...
            'bm_geo_pow', ...
            'bm_bed_height', ...
            'bm_srf_height', ...
            'bm_thick', ...
            'easts', ...
            'geo_pow_calib', ...
            'geo_pow_xover', ...
            'heading', ...
            'lat', ...
            'long', ...
            'norths', ...
            'rdr_clear', ...
            'rdr_dist', ...
            'rdr_geo_pow', ...
            'rdr_height', ...
            'rdr_thick', ...
            'srf_height', ...
            'survey_num', ...
            'reflect', ...
            'atten_rate', ...
            'atten_unc', ...
            'C_0', ...
            'C_min', ...
            'fit_dist', ...
            'bed_slope', ...
            'srf_slope', ...
            'peakiness', ...
            'abrupt', ...
            'geo_pow_max', ...
            'geo_pow_agg', ...
            'max_pow', ...
            'agg_pow'};


fld_nms = fieldnames(results);

for i = 1:length(fld_nms)
    if any(strcmp(fld_nms{i},safe_list))
        safe_results.(fld_nms{i}) = results.(fld_nms{i});
    end
end


end

